version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # 또는 3.7 등 필요한 버전
    commands:
      - echo "Updating pip..."
      - python -m pip install --upgrade pip
      - echo "Installing gunicorn..."
      - pip install gunicorn
      - echo "Installing AWS CLI..."
      - pip install awscli

  build:
    commands:
      - echo "Entering build phase..."
      - echo "Installing dependencies from requirements.txt..."
      - python -m venv .venv
      - . .venv/bin/activate  # source 대신 . 사용
      - pip install -r requirements.txt

      # (선택 사항) 테스트 및 코드 품질 검사
      # - echo "Running unit tests..."
      # - pip install pytest
      # - pytest tests/

      - echo "Running code quality checks..."
      - pip install flake8
      - flake8 .

  post_build:
    commands:
      - echo "Build phase completed on `date`"

      # ... (배포 관련 명령어, 필요에 따라) ...

artifacts:
    files:
      - '**/*'
    discard-paths: yes

# reports:
#     pytest_reports:
#         files:
#             - '**/test-reports/*.xml'
#         base-directory: '.'
#         file-format: JUNITXML