version: 0.2

phases:
  install:
    commands:
      - echo "Removing existing .pyenv directory (if any)..."
      - rm -rf /root/.pyenv
      - echo "Installing pyenv..."
      - curl https://pyenv.run | bash
      - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
      - echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
      - echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init -)"\nfi' >> ~/.bashrc
      - . ~/.bashrc  # source 대신 . 사용
      - echo "Installing Python 3.9.18..."
      - pyenv install 3.9.18
      - pyenv global 3.9.18
      - echo "Updating pip..."
      - python -m pip install --upgrade pip
      - echo "Installing gunicorn and AWS CLI..."
      - pip install gunicorn awscli

  build:
    commands:
      - set -e
      - echo "Entering build phase..."
      - echo "Installing dependencies from requirements.txt..."
      - python -m venv .venv
      - . .venv/bin/activate
      - pip install -r requirements.txt
      # ...

  post_build:
    commands:
      - echo "Build phase completed on `date`"
      - . .venv/bin/activate && \
        nohup gunicorn --workers 3 --bind 0.0.0.0:8000 app:app > gunicorn.log 2>&1 &

artifacts:
  files:
    - app.py
    - templates/**/*
    - static/**/*
    - requirements.txt
  discard-paths: yes